import Head from "next/head";
import Layout from "../components/layout/layout";
import Header from "../components/header/header";
import "../styles/globals.css";

export default function App({ Component, pageProps }) {
	return (
		<Layout>
			<Head>
				<title>Movie</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Component {...pageProps} />
		</Layout>
	);
}
